spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
        - id: product_route
          uri: lb://aqimail-product
          predicates:
            - Path=/api/product/**
          filters:
#            api/下的所有请求路由到aqimail-product,并将/api/重写为/
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: aqimail-member
          uri: lb://aqimail-member
          predicates:
            - Path=/api/member/**
          filters:
              #            api/下的所有请求路由到aqimail-member,并将/api/重写为/
            - RewritePath=/api/(?<segment>.*), /$\{segment}


        - id: third_party_route
          uri: lb://aqimail-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
#            api/下的所有请求路由到aqimail-product,并将/api/重写成/renren-fast/
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
#http://localhost:88/api/captcha.jpg  -->   http://localhost:8080/renren-dast/captcha.jpg