spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: aqimall
      access-key: LTAI5tChWd4jahxzk5xiiyyJ
      secret-key: aWyGHrWL8ttCkkbptSOl0XI3JpexEj
  application:
    name: aqimail-third-party

server:
  port: 33000
